client_config_file: config/client_secrets.json

save_credentials: True
save_credentials_backend: file
save_credentials_file: config/credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.readonly

redirect_uri: http://127.0.0.1:8765/
